version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173" # Client port
      - "3000:3000" # Server port
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - /app/client/node_modules
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "cd /app/server && npm install && npm run dev & cd /app/client && npm install && npm run dev"

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5173:5173" # Client port
      - "3000:3000" # Server port
    environment:
      - NODE_ENV=production
